[variables]
NODE_VERSION = "22.12.0"
NODE_OPTIONS = "--max-old-space-size=4096"

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build -- --configuration=production"
]

[start]
cmd = "node dist/web/server/server.mjs"
